// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using carShop;

#nullable disable

namespace carShop.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20241020170317_Image")]
    partial class Image
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("carShop.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            BodyType = "Coupe",
                            Color = "Red",
                            ImagePath = "https://www.motortrend.com/uploads/sites/5/2020/01/1967-Ford-Mustang-Shelby-GT500-EXP-22Little-Red22.jpg",
                            Model = "Ford Mustang",
                            Year = 1967
                        },
                        new
                        {
                            Id = 3,
                            BodyType = "ORV",
                            Color = "Black",
                            ImagePath = "https://api.auto-star.ua/uploads/cars/bmw_x5_2015_19929/main.jpg",
                            Model = "BMW X5",
                            Year = 2015
                        },
                        new
                        {
                            Id = 4,
                            BodyType = "GT",
                            Color = "Gray",
                            ImagePath = "https://cdn.ferrari.com/cms/network/media/img/resize/5d70e7d4ee5f7e58630608ed-d-2.0-812gts-dynamic-focuson?",
                            Model = "Ferrari 812 GTS",
                            Year = 2017
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
